#pragma once

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.5.0
// Descriptor size: 30 (bytes)
// +----------+-------+-------------------+
// | ReportId | Kind  | ReportSizeInBytes |
// +----------+-------+-------------------+
// |        1 | Input |                 3 |
// +----------+-------+-------------------+
static const uint8_t hidReportDescriptor[] = 
{
    0x05, 0x01,          // UsagePage(Generic Desktop[0x0001])
    0x09, 0x02,          // UsageId(Mouse[0x0002])
    0xA1, 0x01,          // Collection(Application)
    0x85, 0x01,          //     ReportId(1)
    0x09, 0x01,          //     UsageId(Pointer[0x0001])
    0xA1, 0x00,          //     Collection(Physical)
    0x09, 0x30,          //         UsageId(X[0x0030])
    0x09, 0x31,          //         UsageId(Y[0x0031])
    0x16, 0x1E, 0xFB,    //         LogicalMinimum(-1,250)
    0x26, 0xE2, 0x04,    //         LogicalMaximum(1,250)
    0x95, 0x02,          //         ReportCount(2)
    0x75, 0x0C,          //         ReportSize(12)
    0x81, 0x06,          //         Input(Data, Variable, Relative, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                //     EndCollection()
    0xC0,                // EndCollection()
};

#pragma pack(push,1)

#define HID_REPORT_INPUT1_ID (1)
struct HidReportInput1
{
    uint8_t ReportId = HID_REPORT_INPUT1_ID;
    uint8_t Payload[3];
};

#pragma pack(pop)